<?php
use Application\Controller\CoreController;
use Laminas\ServiceManager\Exception\ServiceNotFoundException;
use Laminas\Db\Sql\Select;

# Check if category tag exists
$oTag = CoreController::$aCoreTables['core-tag']->select(['tag_key'=>'category']);
$aFinalTags = [];
if(count($oTag) > 0) {
    $oTag = $oTag->current();
    $oEntityTags = CoreController::$aCoreTables['core-entity-tag']->select(['tag_idfs'=>$oTag->Tag_ID,'entity_form_idfs'=>'skeleton-single']);

    try {
        # Get Skeleton Table
        $oSkeletonTbl = CoreController::$oServiceManager->get(\OnePlace\Skeleton\Model\SkeletonTable::class);

        # Sort Tags by Skeleton Count per Tag
        $aTopTagsByCount = [];
        $aSortArray = [];
        if(count($oEntityTags) > 0) {
            foreach($oEntityTags as $oEntityTag) {
                $iCount = count(CoreController::$aCoreTables['core-entity-tag-entity']->select(['entity_tag_idfs'=>$oEntityTag->Entitytag_ID,'entity_type'=>'skeleton']));
                $aTopTagsByCount[$oEntityTag->Entitytag_ID] = ['iCount'=>$iCount,'oTag'=>$oEntityTag];
                $aSortArray['iCount'][] = $iCount;
            }
        }
        array_multisort($aSortArray['iCount'],SORT_DESC,$aTopTagsByCount);

        # Only show top tags by count
        $iMaxTags = 5;
        $iCount = 0;
        foreach($aTopTagsByCount as $oTmpTag) {
            if($iCount == $iMaxTags) {
                break;
            }
            $aFinalTags[] = $oTmpTag;
            $iCount++;
        }
    } catch(\RuntimeException $e) {

    }
}

# Only show widget if we have tags to show
if(count($aFinalTags) > 0) {
?>
<!-- Skeleton Category Tag Info -->
<div class="col-md-4 col-xl-4">
    <div class="card">
        <div class="card-header">
            <div class="card-actions float-right">
                <div class="dropdown show">
                    <a href="#" data-toggle="dropdown" data-display="static">
                        <i class="align-middle" data-feather="more-horizontal"></i>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </div>
            </div>
            <h5 class="card-title mb-0">
                <?=$this->translate('Skeleton')?> - <?=$this->translate('Category Info')?>
            </h5>
        </div>
        <div class="card-body h-100">
            <ul class="list-group">
                <?php
                # Show top tags
                foreach($aFinalTags as $aInfo) {
                    $oEntityTag = $aInfo['oTag'];
                    $iCount = $aInfo['iCount']; ?>
                    <li class="list-group-item">
                        <?=$oEntityTag->tag_value?> <span class="badge badge-dark float-right" style="font-size:18px"><?=$iCount?></span>
                    </li>
                <?php
                }
                ?>
            </ul>
        </div>
    </div>
</div>
    <!-- Skeleton Category Tag Info -->
<?php
}
?>