<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Skeleton - onePlace X - RC 1')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('vendor/jquery-ui/jquery-uia.min.css'))
        ->prependStylesheet($this->basePath('vendor/fontawesome/css/all.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/listener.js'))
        ->prependFile($this->basePath('vendor/jquery-ui/jquery-ui.min.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.4.1.min.js'))
    ?>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" height="28" alt="Laminas MVC Skeleton"/>&nbsp;onePlace X
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('skeleton') ?>">Skeleton</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="<?= $this->url('user') ?>">User</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->url('logout') ?>">Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?= $this->partial('partial/breadcrumb', ['aButtons'=>isset($this->aButtons) ? $this->aButtons : [], 'pages'=>[]]); ?>
    <?= $this->content ?>
    <hr>
    <footer>
        <p>&copy; 2010-<?= date('Y') ?> by Verein onePlace. Alle Rechte vorbehalten.</p>
    </footer>
</div>
<?= $this->inlineScript() ?>
</body>
</html>
