<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h2>Find Contact</h2>
            </div>
            <?php if(isset($aResults)) { ?>

            <?php } else { ?>
            <form action="" method="post">
                <div class="card-body">
                    <?= $this->partial('partial/basictabs', ['sFormName'=>$this->sFormName]); ?>
                    <?= $this->partial('partial/searchtabcontents', ['sFormName'=>$this->sFormName]); ?>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit">
                        Start Search
                    </button>
                </div>
            </form>
            <?php } ?>
        </div>
    </div>
    <?php if(isset($aResults)) { ?>
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2>Results</h2>
                </div>
                <div class="card-body">

                </div>
            </div>
        </div>
    <?php } ?>
</div>
